/*
  Warnings:

  - You are about to drop the `aws_resource` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "aws_resource" DROP CONSTRAINT "aws_resource_organizationId_fkey";

-- DropForeignKey
ALTER TABLE "aws_resource" DROP CONSTRAINT "aws_resource_workspaceId_fkey";

-- DropTable
DROP TABLE "aws_resource";

-- CreateTable
CREATE TABLE "resource" (
    "id" SERIAL NOT NULL,
    "organizationId" INTEGER NOT NULL,
    "workspaceId" INTEGER NOT NULL,
    "provider" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "resourceType" TEXT NOT NULL,
    "resourceName" TEXT NOT NULL,
    "resourceId" TEXT NOT NULL,
    "stateFile" TEXT NOT NULL,
    "scannedStateFile" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "autogenerated" BOOLEAN NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "awsAccountId" INTEGER,

    CONSTRAINT "resource_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "resource_awsAccountId_resourceType_resourceId_key" ON "resource"("awsAccountId", "resourceType", "resourceId");

-- AddForeignKey
ALTER TABLE "resource" ADD CONSTRAINT "resource_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "resource" ADD CONSTRAINT "resource_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "resource" ADD CONSTRAINT "resource_awsAccountId_fkey" FOREIGN KEY ("awsAccountId") REFERENCES "aws_account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
