-- CreateTable
CREATE TABLE "aws_resource" (
    "id" SERIAL NOT NULL,
    "organizationId" INTEGER NOT NULL,
    "provider" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "resourceType" TEXT NOT NULL,
    "resourceName" TEXT NOT NULL,
    "resourceId" TEXT NOT NULL,
    "stateFile" TEXT NOT NULL,
    "scannedStateFile" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "autogenerated" BOOLEAN NOT NULL,
    "description" TEXT,

    CONSTRAINT "aws_resource_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "aws_resource" ADD CONSTRAINT "aws_resource_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
